version: '2'
services:
  app:
    image: nevalla/todo-example:latest
    extends:
      file: docker-compose.yml
      service: web
    instances: 3
    environment:
      - MONGODB_URI=mongodb://${project}-mongodb.kontena.local/todo_production

  mongodb:
    image: mongo:3.2
    command: mongod --smallfiles
    stateful: true
